# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gsp.models


class Migration(migrations.Migration):

    dependencies = [
        ('gsp', '0007_auto_20170310_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('picture', models.ImageField(upload_to=gsp.models.user_directory_path)),
                ('rating', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsp.UserProfile')),
            ],
        ),
    ]
