# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsp', '0008_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.RemoveField(
            model_name='page',
            name='views',
        ),
        migrations.AddField(
            model_name='page',
            name='img',
            field=models.CharField(default='Super Hans.jpg', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gsp.Category'),
            preserve_default=False,
        ),
    ]
