# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsp', '0010_auto_20170317_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='img',
            field=models.CharField(default='Super Hans.jpg', max_length=128),
        ),
    ]
