# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsp', '0011_auto_20170317_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='category',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='user',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
