# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsp', '0012_auto_20170317_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gsp.Category'),
        ),
    ]
