# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsp', '0015_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gsp.Category'),
            preserve_default=False,
        ),
    ]
