# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gsp', '0016_upload_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
