# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsp', '0025_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favourites',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gsp.Upload'),
            preserve_default=False,
        ),
    ]
