# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsp', '0028_remove_upload_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
