# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0003_auto_20160721_1127'),
        ('gsp', '0029_upload_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='rating',
        ),
        migrations.AddField(
            model_name='upload',
            name='ratings',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='star_ratings.Rating'),
            preserve_default=False,
        ),
    ]
