# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gsp', '0030_auto_20170323_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
